#Appication Config
server:
  port: 9091
  error:
    whitelabel:
      enabled: false
  
spring:
  application:
    name: Exchange-Rates-Microservice-Load
    
  h2:
    console:
      enabled: true
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        proc:
          param_null_passing: true
    
    hibernate:
      ddl-auto: update
      generate-ddl: true      
  
  
#Eureka Config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    hostname: localhost         
     
#logging.level.org.hibernate.SQL=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework=ERROR